development:
  adapter: postgresql
  encoding: unicode
  database: proyecto

  username: legosc
  password: g.j.7811

test:
  adapter: postgresql
  encoding: unicode
  database: proyecto_test

  username: legosc
  password: g.j.7811
